### ISSUE TITLE
The members of the Adapter  are named in lowercase letters，so cannot assign values ​​outside the package

### ISSUE THREAD

**Issue by believening** [vance-liu/gdb-adapter#3]
The members of the Adapter  are named in lowercase letters，so cannot assign values ​​outside the package

```
// Adapter represents the gdb adapter for policy storage.
type Adapter struct {
	driverName     string
	dataSourceName string
	tableName      string
	db             gdb.DB
}
```

**Comment by hsluoyz** [comment]
@closetool plz make a PR to fix it.

**Comment by hsluoyz** [comment]
@vance-liu plz make a new GitHub release.

**Comment by vance-liu** [comment]
@hsluoyz Thank you for your reminder, [V0.1.0](https://github.com/vance-liu/gdb-adapter/releases/tag/V0.1.0) is released.

**Comment by hsluoyz** [comment]
@believening https://github.com/vance-liu/gdb-adapter/releases/tag/V0.1.0
